import type { Metadata } from "next"
import localFont from "next/font/local"

import "@/styles/globals.css"

const Inter = localFont({
  src: "../public/fonts/Inter.ttf",
  display: "swap",
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${Inter.variable} font-inter antialiased`}>
        {children}
      </body>
    </html>
  )
}
